### PR TITLE
WE-000 | Create base API service modules

### PR DESCRIPTION
**Pull request by Noya-19**
Until a schema is provided and more specific services can be created, these are the base modules that the front-end will use to interface with our database.

### CODE REVIEW

**Review by HeroofLight555 — APPROVED** [review]
I think it looks good 👍

**Review by sammax12 — APPROVED** [review]
I think the base front API service looks good!

**Comment by sahag98** [comment]
Looks good to me

**Review by sahag98 — COMMENTED** [review]
Looks pretty good!

**Review by sahag98 — COMMENTED** [review]
Looks good!

**Pull request merged**
